Repository Apoorv-cloud/1_Hacktoberfest-22, pull requests merged in 2022-10, with the labels that each got.

#4 Apoorv's Playlist
  index.html
Labels: hacktoberfest-accepted

#5 New
  .idea/.gitignore
  .idea/1_Hacktoberfest-22.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  index.html
Labels: hacktoberfest-accepted

#15 Playlist2
  index.html
Labels: hacktoberfest-accepted

#17 Add the playlist
  index.html
Labels: hacktoberfest-accepted

#11 Added my playlist Chill Mood
  index.html
Labels: hacktoberfest-accepted

#16 Added Playlist
  index.html
Labels: hacktoberfest-accepted

#19 Update index.html
  index.html
Labels: hacktoberfest-accepted

#22 playlist#2
  index.html
Labels: hacktoberfest-accepted

#23 Action
  index.html
Labels: hacktoberfest-accepted

#24 Anime
  index.html
Labels: hacktoberfest-accepted

#37 playlist#1
  index.html
Labels: hacktoberfest-accepted

#33 New playlist
  index.html
Labels: hacktoberfest-accepted

#35 Aakanksha 2nd playlist
  index.html
Labels: hacktoberfest-accepted

#36 Aakanksha 3rd playlist
  index.html
Labels: hacktoberfest-accepted

#27 playlist#3
  index.html
Labels: hacktoberfest-accepted

#29 Add Main Display Section
  index.html
  style.css
Labels: hacktoberfest-accepted

#26 updated index.html
  index.html
Labels: hacktoberfest-accepted

#32 Anchal added a playlist
  index.html
Labels: hacktoberfest-accepted

#38 Update index.html
  index.html
Labels: hacktoberfest-accepted

#45 Playlist 1
  index.html
Labels: hacktoberfest-accepted

#40 Updated the files index.js, index.html and styles.css
  index.html
  index.js
  style.css
Labels: hacktoberfest'22, hacktoberfest-accepted

#59 Sameer - Playlist Added !
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#56 Playlist#2
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#53 Playlist#3
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#54 Playlist#4
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#51 new playlist added
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#61 Playlist#4
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#76 4th_playlist
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#71 text_in_playlist
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#70 playlist #4
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#69 Updated Playlist !
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#63 Added my playlist
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#80 Playlist#5
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#83 2nd playlist
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#89 Playlist added
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#88 Add a new playlist
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#85 Update index.html
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#93 Added Deepak Jain's card
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#94 Kartikey's Playlist
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#95 Harsh Dhama's Playlist
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#98 Added playlist
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#99 First Playlist Added
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#102 second playlist added
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#103 myplaylist
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#104 updated-by-utkarsh
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#105 added playlists again
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#106 Playlist added
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#107 spotify playlist card added
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#108 Add a playlist
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#110 Jatin 2
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#111 Mishra
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#113 I have added my spotify playlist
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#114 hello..i have added my spotify playlist
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#117 PetrolHead playlist added
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#118 EFT playlist added.
  index.html
Labels: hacktoberfest'22, hacktoberfest-accepted

#120 added playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#121 updated cover image for my playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#124 Two
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#126 added playlist and profile
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#128 Added another playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#129 added my playlist
  .vscode/settings.json
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#132 My first Playlist - Prajwal
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#133 Playlist2
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#134 Created card
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#136 Newbranch1
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#137 image added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#138 Playlist added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#139 Added Playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#142 First Playlist Added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#143 newplaylist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#144 Playlist2
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#146 playlist1
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#150 Second playlist of spotify of Samrat added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#152 playlist added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#157 Playlist added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#158 spotify playlist
  index.html
  playlist
Labels: hacktoberfest, hacktoberfest-accepted

#159 song playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#160 Update index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#162 playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#161 Aarna's playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#165 One Sided Love Playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#166 English LoFi Love Playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#167 Update index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#170 Playlist added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#171 Playlist Added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#178 Change 1
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#179 Change 2
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#180 Change 3
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#181 Change 4
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#177 Updated fork
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#182 Change 5
  .idea/.gitignore
  .idea/1_Hacktoberfest-22.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: hacktoberfest, hacktoberfest-accepted

#183 Change 6
  .vscode/settings.json
Labels: hacktoberfest, hacktoberfest-accepted

#184 4th commit
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#186 Update index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#187 Add my playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#188 Please add my playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#189 Added my playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#191 harsh saxena playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#194 Playlist added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#195 Playlist added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#197 Update index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#201 Harshsaxena main2
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#205 added third playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#209 Update index.html: by Tanvi
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#211 Tanvi: added 2nd playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#212 Playlist added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#216 2nd Playlist Added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#219 Kush Agarwal playlist added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#220 Added 3rd card: Tanvi
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#221 Third Playlist Added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#203 KK's Playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#226 Edits in card: by Tanvi
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#228 Harsh saxena added playlist
  .vscode/settings.json
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#229 brlmember
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#230 Brlnewplaylist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#231 yash
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#232 Yash2
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#234 added my spotify card
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#237 emoticon added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#240 Jatin addition
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#241 add my update
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#242 Add my new playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#243 updated the cover image of my playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#244 Added playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#245 Update index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#246 First Playlist added.
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#247 Transformers Playlist Added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#251 mona placecard
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#252 playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#254 Added playlist
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#255 Third playlist added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#256 Fourth playlist added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#257 change
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#259 Samrat25
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#248 Linkin Park Playlist Added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted
